!function(e){var t={};function n(o){if(t[o])return t[o].exports;var r=t[o]={i:o,l:!1,exports:{}};return e[o].call(r.exports,r,r.exports,n),r.l=!0,r.exports}n.m=e,n.c=t,n.d=function(e,t,o){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:o})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var r in e)n.d(o,r,function(t){return e[t]}.bind(null,r));return o},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./node_modules/babel-loader/lib/index.js?!./node_modules/scratch-vm/src/extension-support/tw-iframe-extension-worker-entry.js")}({"./node_modules/babel-loader/lib/index.js?!./node_modules/scratch-vm/src/extension-support/tw-iframe-extension-worker-entry.js":
/*!***********************************************************************************************************************************!*\
  !*** ./node_modules/babel-loader/lib??ref--4!./node_modules/scratch-vm/src/extension-support/tw-iframe-extension-worker-entry.js ***!
  \***********************************************************************************************************************************/
/*! no static exports found */function(e,t,n){(function(e){const t=n(/*! ./tw-extension-worker-context */"./node_modules/scratch-vm/src/extension-support/tw-extension-worker-context.js"),o=n(/*! ./tw-jquery-shim */"./node_modules/scratch-vm/src/extension-support/tw-jquery-shim.js");e.$=o,e.jQuery=o;const r=window.__WRAPPED_IFRAME_ID__;t.isWorker=!1,t.centralDispatchService={postMessage(e,t){const n={vmIframeId:r,message:e};t?window.parent.postMessage(n,"*",t):window.parent.postMessage(n,"*")}},n(/*! ./extension-worker */"./node_modules/scratch-vm/src/extension-support/extension-worker.js"),window.parent.postMessage({vmIframeId:r,ready:!0},"*")}).call(this,n(/*! ./../../../webpack/buildin/global.js */"./node_modules/webpack/buildin/global.js"))},"./node_modules/microee/index.js":
/*!***************************************!*\
  !*** ./node_modules/microee/index.js ***!
  \***************************************/
/*! no static exports found */function(e,t){function n(){this._events={}}n.prototype={on:function(e,t){this._events||(this._events={});var n=this._events;return(n[e]||(n[e]=[])).push(t),this},removeListener:function(e,t){var n,o=this._events[e]||[];for(n=o.length-1;n>=0&&o[n];n--)o[n]!==t&&o[n].cb!==t||o.splice(n,1)},removeAllListeners:function(e){e?this._events[e]&&(this._events[e]=[]):this._events={}},listeners:function(e){return this._events&&this._events[e]||[]},emit:function(e){this._events||(this._events={});var t,n=Array.prototype.slice.call(arguments,1),o=this._events[e]||[];for(t=o.length-1;t>=0&&o[t];t--)o[t].apply(this,n);return this},when:function(e,t){return this.once(e,t,!0)},once:function(e,t,n){if(!t)return this;function o(){n||this.removeListener(e,o),t.apply(this,arguments)&&n&&this.removeListener(e,o)}return o.cb=t,this.on(e,o),this}},n.mixin=function(e){var t,o=n.prototype;for(t in o)o.hasOwnProperty(t)&&(e.prototype[t]=o[t])},e.exports=n},"./node_modules/minilog/lib/common/filter.js":
/*!***************************************************!*\
  !*** ./node_modules/minilog/lib/common/filter.js ***!
  \***************************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ./transform.js */"./node_modules/minilog/lib/common/transform.js"),r={debug:1,info:2,warn:3,error:4};function s(){this.enabled=!0,this.defaultResult=!0,this.clear()}function i(e,t){return e.n.test?e.n.test(t):e.n==t}o.mixin(s),s.prototype.allow=function(e,t){return this._white.push({n:e,l:r[t]}),this},s.prototype.deny=function(e,t){return this._black.push({n:e,l:r[t]}),this},s.prototype.clear=function(){return this._white=[],this._black=[],this},s.prototype.test=function(e,t){var n,o=Math.max(this._white.length,this._black.length);for(n=0;n<o;n++){if(this._white[n]&&i(this._white[n],e)&&r[t]>=this._white[n].l)return!0;if(this._black[n]&&i(this._black[n],e)&&r[t]<=this._black[n].l)return!1}return this.defaultResult},s.prototype.write=function(e,t,n){if(!this.enabled||this.test(e,t))return this.emit("item",e,t,n)},e.exports=s},"./node_modules/minilog/lib/common/minilog.js":
/*!****************************************************!*\
  !*** ./node_modules/minilog/lib/common/minilog.js ***!
  \****************************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ./transform.js */"./node_modules/minilog/lib/common/transform.js"),r=n(/*! ./filter.js */"./node_modules/minilog/lib/common/filter.js"),s=new o,i=Array.prototype.slice;(t=e.exports=function(e){var n=function(){return s.write(e,void 0,i.call(arguments)),n};return n.debug=function(){return s.write(e,"debug",i.call(arguments)),n},n.info=function(){return s.write(e,"info",i.call(arguments)),n},n.warn=function(){return s.write(e,"warn",i.call(arguments)),n},n.error=function(){return s.write(e,"error",i.call(arguments)),n},n.log=n.debug,n.suggest=t.suggest,n.format=s.format,n}).defaultBackend=t.defaultFormatter=null,t.pipe=function(e){return s.pipe(e)},t.end=t.unpipe=t.disable=function(e){return s.unpipe(e)},t.Transform=o,t.Filter=r,t.suggest=new r,t.enable=function(){return t.defaultFormatter?s.pipe(t.suggest).pipe(t.defaultFormatter).pipe(t.defaultBackend):s.pipe(t.suggest).pipe(t.defaultBackend)}},"./node_modules/minilog/lib/common/transform.js":
/*!******************************************************!*\
  !*** ./node_modules/minilog/lib/common/transform.js ***!
  \******************************************************/
/*! no static exports found */function(e,t,n){function o(){}n(/*! microee */"./node_modules/microee/index.js").mixin(o),o.prototype.write=function(e,t,n){this.emit("item",e,t,n)},o.prototype.end=function(){this.emit("end"),this.removeAllListeners()},o.prototype.pipe=function(e){var t=this;function n(){e.write.apply(e,Array.prototype.slice.call(arguments))}function o(){!e._isStdio&&e.end()}return t.emit("unpipe",e),e.emit("pipe",t),t.on("item",n),t.on("end",o),t.when("unpipe",(function(r){var s=r===e||void 0===r;return s&&(t.removeListener("item",n),t.removeListener("end",o),e.emit("unpipe")),s})),e},o.prototype.unpipe=function(e){return this.emit("unpipe",e),this},o.prototype.format=function(e){throw new Error(["Warning: .format() is deprecated in Minilog v2! Use .pipe() instead. For example:","var Minilog = require('minilog');","Minilog","  .pipe(Minilog.backends.console.formatClean)","  .pipe(Minilog.backends.console);"].join("\n"))},o.mixin=function(e){var t,n=o.prototype;for(t in n)n.hasOwnProperty(t)&&(e.prototype[t]=n[t])},e.exports=o},"./node_modules/minilog/lib/web/array.js":
/*!***********************************************!*\
  !*** ./node_modules/minilog/lib/web/array.js ***!
  \***********************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ../common/transform.js */"./node_modules/minilog/lib/common/transform.js"),r=[],s=new o;s.write=function(e,t,n){r.push([e,t,n])},s.get=function(){return r},s.empty=function(){r=[]},e.exports=s},"./node_modules/minilog/lib/web/console.js":
/*!*************************************************!*\
  !*** ./node_modules/minilog/lib/web/console.js ***!
  \*************************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ../common/transform.js */"./node_modules/minilog/lib/common/transform.js"),r=/\n+$/,s=new o;s.write=function(e,t,n){var o=n.length-1;if("undefined"!=typeof console&&console.log){if(console.log.apply)return console.log.apply(console,[e,t].concat(n));if(JSON&&JSON.stringify){n[o]&&"string"==typeof n[o]&&(n[o]=n[o].replace(r,""));try{for(o=0;o<n.length;o++)n[o]=JSON.stringify(n[o])}catch(e){}console.log(n.join(" "))}}},s.formatters=["color","minilog"],s.color=n(/*! ./formatters/color.js */"./node_modules/minilog/lib/web/formatters/color.js"),s.minilog=n(/*! ./formatters/minilog.js */"./node_modules/minilog/lib/web/formatters/minilog.js"),e.exports=s},"./node_modules/minilog/lib/web/formatters/color.js":
/*!**********************************************************!*\
  !*** ./node_modules/minilog/lib/web/formatters/color.js ***!
  \**********************************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ../../common/transform.js */"./node_modules/minilog/lib/common/transform.js"),r=n(/*! ./util.js */"./node_modules/minilog/lib/web/formatters/util.js"),s={debug:["cyan"],info:["purple"],warn:["yellow",!0],error:["red",!0]},i=new o;i.write=function(e,t,n){console.log;console[t]&&console[t].apply&&console[t].apply(console,["%c"+e+" %c"+t,r("gray"),r.apply(r,s[t])].concat(n))},i.pipe=function(){},e.exports=i},"./node_modules/minilog/lib/web/formatters/minilog.js":
/*!************************************************************!*\
  !*** ./node_modules/minilog/lib/web/formatters/minilog.js ***!
  \************************************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ../../common/transform.js */"./node_modules/minilog/lib/common/transform.js"),r=n(/*! ./util.js */"./node_modules/minilog/lib/web/formatters/util.js"),s={debug:["gray"],info:["purple"],warn:["yellow",!0],error:["red",!0]},i=new o;i.write=function(e,t,n){var o=console.log;"debug"!=t&&console[t]&&(o=console[t]);var i=0;if("info"!=t){for(;i<n.length&&"string"==typeof n[i];i++);o.apply(console,["%c"+e+" "+n.slice(0,i).join(" "),r.apply(r,s[t])].concat(n.slice(i)))}else o.apply(console,["%c"+e,r.apply(r,s[t])].concat(n))},i.pipe=function(){},e.exports=i},"./node_modules/minilog/lib/web/formatters/util.js":
/*!*********************************************************!*\
  !*** ./node_modules/minilog/lib/web/formatters/util.js ***!
  \*********************************************************/
/*! no static exports found */function(e,t){var n={black:"#000",red:"#c23621",green:"#25bc26",yellow:"#bbbb00",blue:"#492ee1",magenta:"#d338d3",cyan:"#33bbc8",gray:"#808080",purple:"#708"};e.exports=function(e,t){return t?"color: #fff; background: "+n[e]+";":"color: "+n[e]+";"}},"./node_modules/minilog/lib/web/index.js":
/*!***********************************************!*\
  !*** ./node_modules/minilog/lib/web/index.js ***!
  \***********************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ../common/minilog.js */"./node_modules/minilog/lib/common/minilog.js"),r=o.enable,s=o.disable,i="undefined"!=typeof navigator&&/chrome/i.test(navigator.userAgent),c=n(/*! ./console.js */"./node_modules/minilog/lib/web/console.js");if(o.defaultBackend=i?c.minilog:c,"undefined"!=typeof window){try{o.enable(JSON.parse(window.localStorage.minilogSettings))}catch(e){}if(window.location&&window.location.search){var a=RegExp("[?&]minilog=([^&]*)").exec(window.location.search);a&&o.enable(decodeURIComponent(a[1]))}}o.enable=function(){r.call(o,!0);try{window.localStorage.minilogSettings=JSON.stringify(!0)}catch(e){}return this},o.disable=function(){s.call(o);try{delete window.localStorage.minilogSettings}catch(e){}return this},(e.exports=o).backends={array:n(/*! ./array.js */"./node_modules/minilog/lib/web/array.js"),browser:o.defaultBackend,localStorage:n(/*! ./localstorage.js */"./node_modules/minilog/lib/web/localstorage.js"),jQuery:n(/*! ./jquery_simple.js */"./node_modules/minilog/lib/web/jquery_simple.js")}},"./node_modules/minilog/lib/web/jquery_simple.js":
/*!*******************************************************!*\
  !*** ./node_modules/minilog/lib/web/jquery_simple.js ***!
  \*******************************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ../common/transform.js */"./node_modules/minilog/lib/common/transform.js"),r=(new Date).valueOf().toString(36);function s(e){this.url=e.url||"",this.cache=[],this.timer=null,this.interval=e.interval||3e4,this.enabled=!0,this.jQuery=window.jQuery,this.extras={}}o.mixin(s),s.prototype.write=function(e,t,n){this.timer||this.init(),this.cache.push([e,t].concat(n))},s.prototype.init=function(){if(this.enabled&&this.jQuery){var e=this;this.timer=setTimeout((function(){var t,n,o=[],s=e.url;if(0==e.cache.length)return e.init();for(t=0;t<e.cache.length;t++)try{JSON.stringify(e.cache[t]),o.push(e.cache[t])}catch(e){}e.jQuery.isEmptyObject(e.extras)?(n=JSON.stringify({logs:o}),s=e.url+"?client_id="+r):n=JSON.stringify(e.jQuery.extend({logs:o},e.extras)),e.jQuery.ajax(s,{type:"POST",cache:!1,processData:!1,data:n,contentType:"application/json",timeout:1e4}).success((function(t,n,o){t.interval&&(e.interval=Math.max(1e3,t.interval))})).error((function(){e.interval=3e4})).always((function(){e.init()})),e.cache=[]}),this.interval)}},s.prototype.end=function(){},s.jQueryWait=function(e){if("undefined"!=typeof window&&(window.jQuery||window.$))return e(window.jQuery||window.$);"undefined"!=typeof window&&setTimeout((function(){s.jQueryWait(e)}),200)},e.exports=s},"./node_modules/minilog/lib/web/localstorage.js":
/*!******************************************************!*\
  !*** ./node_modules/minilog/lib/web/localstorage.js ***!
  \******************************************************/
/*! no static exports found */function(e,t,n){var o=n(/*! ../common/transform.js */"./node_modules/minilog/lib/common/transform.js"),r=!1,s=new o;s.write=function(e,t,n){if("undefined"!=typeof window&&"undefined"!=typeof JSON&&JSON.stringify&&JSON.parse)try{r||(r=window.localStorage.minilog?JSON.parse(window.localStorage.minilog):[]),r.push([(new Date).toString(),e,t,n]),window.localStorage.minilog=JSON.stringify(r)}catch(e){}},e.exports=s},"./node_modules/scratch-vm/src/dispatch/shared-dispatch.js":
/*!*****************************************************************!*\
  !*** ./node_modules/scratch-vm/src/dispatch/shared-dispatch.js ***!
  \*****************************************************************/
/*! no static exports found */function(e,t,n){const o=n(/*! ../util/log */"./node_modules/scratch-vm/src/util/log.js");e.exports=class{constructor(){this.callbacks=[],this.nextResponseId=0}call(e,t,...n){return this.transferCall(e,t,null,...n)}transferCall(e,t,n,...o){try{const{provider:r,isRemote:s}=this._getServiceProvider(e);if(r){if(s)return this._remoteTransferCall(r,e,t,n,...o);const i=r[t].apply(r,o);return Promise.resolve(i)}return Promise.reject(new Error("Service not found: ".concat(e)))}catch(e){return Promise.reject(e)}}_isRemoteService(e){return this._getServiceProvider(e).isRemote}_remoteCall(e,t,n,...o){return this._remoteTransferCall(e,t,n,null,...o)}_remoteTransferCall(e,t,n,o,...r){return new Promise((s,i)=>{const c=this._storeCallbacks(s,i);r.length>0&&"function"==typeof r[r.length-1].func&&(r.pop(),r.pop()),o?e.postMessage({service:t,method:n,responseId:c,args:r},o):e.postMessage({service:t,method:n,responseId:c,args:r})})}_storeCallbacks(e,t){const n=this.nextResponseId++;return this.callbacks[n]=[e,t],n}_deliverResponse(e,t){try{const[n,o]=this.callbacks[e];delete this.callbacks[e],t.error?o(t.error):n(t.result)}catch(e){o.error("Dispatch callback failed: ".concat(e))}}_onMessage(e,t){const n=t.data;let r;n.args=n.args||[],n.service?r="dispatch"===n.service?this._onDispatchMessage(e,n):this.call(n.service,n.method,...n.args):void 0===n.responseId?o.error("Dispatch caught malformed message from a worker: ".concat(JSON.stringify(t))):this._deliverResponse(n.responseId,n),r&&(void 0===n.responseId?o.error("Dispatch message missing required response ID: ".concat(JSON.stringify(t))):r.then(t=>e.postMessage({responseId:n.responseId,result:t}),t=>e.postMessage({responseId:n.responseId,error:"".concat(t)})))}_getServiceProvider(e){throw new Error("Could not get provider for ".concat(e,": _getServiceProvider not implemented"))}_onDispatchMessage(e,t){throw new Error("Unimplemented dispatch message handler cannot handle ".concat(t.method," method"))}}},"./node_modules/scratch-vm/src/dispatch/worker-dispatch.js":
/*!*****************************************************************!*\
  !*** ./node_modules/scratch-vm/src/dispatch/worker-dispatch.js ***!
  \*****************************************************************/
/*! no static exports found */function(e,t,n){const o=n(/*! ./shared-dispatch */"./node_modules/scratch-vm/src/dispatch/shared-dispatch.js"),r=n(/*! ../util/log */"./node_modules/scratch-vm/src/util/log.js"),{centralDispatchService:s}=n(/*! ../extension-support/tw-extension-worker-context */"./node_modules/scratch-vm/src/extension-support/tw-extension-worker-context.js");e.exports=new class extends o{constructor(){super(),this._connectionPromise=new Promise(e=>{this._onConnect=e}),this.services={},this._onMessage=this._onMessage.bind(this,s),"undefined"!=typeof self&&(self.onmessage=this._onMessage)}get waitForConnection(){return this._connectionPromise}setService(e,t){return this.services.hasOwnProperty(e)&&r.warn("Worker dispatch replacing existing service provider for ".concat(e)),this.services[e]=t,this.waitForConnection.then(()=>this._remoteCall(s,"dispatch","setService",e))}_getServiceProvider(e){const t=this.services[e];return{provider:t||s,isRemote:!t}}_onDispatchMessage(e,t){let n;switch(t.method){case"handshake":n=this._onConnect();break;case"terminate":setTimeout(()=>self.close(),0),n=Promise.resolve();break;default:r.error("Worker dispatch received message for unknown method: ".concat(t.method))}return n}}},"./node_modules/scratch-vm/src/extension-support/argument-type.js":
/*!************************************************************************!*\
  !*** ./node_modules/scratch-vm/src/extension-support/argument-type.js ***!
  \************************************************************************/
/*! no static exports found */function(e,t){e.exports={ANGLE:"angle",BOOLEAN:"Boolean",COLOR:"color",NUMBER:"number",STRING:"string",MATRIX:"matrix",NOTE:"note",IMAGE:"image"}},"./node_modules/scratch-vm/src/extension-support/block-type.js":
/*!*********************************************************************!*\
  !*** ./node_modules/scratch-vm/src/extension-support/block-type.js ***!
  \*********************************************************************/
/*! no static exports found */function(e,t){e.exports={BOOLEAN:"Boolean",BUTTON:"button",COMMAND:"command",CONDITIONAL:"conditional",EVENT:"event",HAT:"hat",LOOP:"loop",REPORTER:"reporter"}},"./node_modules/scratch-vm/src/extension-support/extension-worker.js":
/*!***************************************************************************!*\
  !*** ./node_modules/scratch-vm/src/extension-support/extension-worker.js ***!
  \***************************************************************************/
/*! no static exports found */function(e,t,n){(function(e){const t=n(/*! ../extension-support/argument-type */"./node_modules/scratch-vm/src/extension-support/argument-type.js"),o=n(/*! ../extension-support/block-type */"./node_modules/scratch-vm/src/extension-support/block-type.js"),r=n(/*! ../dispatch/worker-dispatch */"./node_modules/scratch-vm/src/dispatch/worker-dispatch.js"),s=n(/*! ../util/log */"./node_modules/scratch-vm/src/util/log.js"),i=n(/*! ../extension-support/target-type */"./node_modules/scratch-vm/src/extension-support/target-type.js"),{isWorker:c}=n(/*! ./tw-extension-worker-context */"./node_modules/scratch-vm/src/extension-support/tw-extension-worker-context.js");e.Scratch=e.Scratch||{},e.Scratch.ArgumentType=t,e.Scratch.BlockType=o,e.Scratch.TargetType=i;const a=new class{constructor(){this.nextExtensionId=0,this.initialRegistrations=[],this.firstRegistrationPromise=new Promise(e=>{this.firstRegistrationCallback=e}),r.waitForConnection.then(()=>{r.call("extensions","allocateWorker").then(async e=>{const[t,n]=e;this.workerId=t;try{await(e=>{if(!c)return new Promise((t,n)=>{const o=document.createElement("script");o.onload=()=>t(),o.onerror=()=>n(new Error("Error when loading custom extension script: ".concat(e))),o.src=e,document.body.appendChild(o)});importScripts(e)})(n),await this.firstRegistrationPromise;const e=this.initialRegistrations;this.initialRegistrations=null,Promise.all(e).then(()=>r.call("extensions","onWorkerInit",t))}catch(e){s.error(e),r.call("extensions","onWorkerInit",t,"".concat(e))}})}),this.extensions=[]}register(e){const t=this.nextExtensionId++;this.extensions.push(e);const n="extension.".concat(this.workerId,".").concat(t),o=r.setService(n,e).then(()=>r.call("extensions","registerExtensionService",n));return this.initialRegistrations&&(this.firstRegistrationCallback(),this.initialRegistrations.push(o)),o}};e.Scratch.extensions={register:a.register.bind(a)},e.ScratchExtensions=n(/*! ./tw-scratchx-compatibility-layer */"./node_modules/scratch-vm/src/extension-support/tw-scratchx-compatibility-layer.js")}).call(this,n(/*! ./../../../webpack/buildin/global.js */"./node_modules/webpack/buildin/global.js"))},"./node_modules/scratch-vm/src/extension-support/target-type.js":
/*!**********************************************************************!*\
  !*** ./node_modules/scratch-vm/src/extension-support/target-type.js ***!
  \**********************************************************************/
/*! no static exports found */function(e,t){e.exports={SPRITE:"sprite",STAGE:"stage"}},"./node_modules/scratch-vm/src/extension-support/tw-extension-worker-context.js":
/*!**************************************************************************************!*\
  !*** ./node_modules/scratch-vm/src/extension-support/tw-extension-worker-context.js ***!
  \**************************************************************************************/
/*! no static exports found */function(e,t){e.exports={isWorker:!0,centralDispatchService:self}},"./node_modules/scratch-vm/src/extension-support/tw-jquery-shim.js":
/*!*************************************************************************!*\
  !*** ./node_modules/scratch-vm/src/extension-support/tw-jquery-shim.js ***!
  \*************************************************************************/
/*! no static exports found */function(e,t,n){(function(t){const o=n(/*! ../util/log */"./node_modules/scratch-vm/src/util/log.js"),r=()=>{throw new Error("Not implemented")};r.getScript=(e,t)=>{const n=document.createElement("script");n.src=e,t&&(n.onload=()=>t()),document.body.appendChild(n)};let s=0;r.ajax=async(e,n)=>{let i={};e&&n?(i=n,i.url=e):e&&(i=e);const c=(e=>{const t=new URLSearchParams;if(e)for(const n of Object.keys(e))t.set(n,e[n]);return t})(i.data),a=()=>{const e=c.toString();let t=i.url;return e&&(t+="?".concat(e)),t.startsWith("http://")&&(t=t.replace("http://","https://")),t},l=e=>{i.success&&i.success(e)};try{if("jsonp"===i.dataType){const e="_jsonp_callback".concat(s++);t[e]=n=>{delete t[e],l(n)};const n=i.jsonp||"callback";return c.set(n,e),void r.getScript(a())}if("script"===i.dataType)return void r.getScript(a(),l);const e=await fetch(a(),{headers:i.headers});l(await e.json())}catch(e){u=e,o.error(u),i.error&&i.error(u)}var u},e.exports=r}).call(this,n(/*! ./../../../webpack/buildin/global.js */"./node_modules/webpack/buildin/global.js"))},"./node_modules/scratch-vm/src/extension-support/tw-scratchx-compatibility-layer.js":
/*!******************************************************************************************!*\
  !*** ./node_modules/scratch-vm/src/extension-support/tw-scratchx-compatibility-layer.js ***!
  \******************************************************************************************/
/*! no static exports found */function(e,t,n){const o=n(/*! ./argument-type */"./node_modules/scratch-vm/src/extension-support/argument-type.js"),r=n(/*! ./block-type */"./node_modules/scratch-vm/src/extension-support/block-type.js"),{argumentIndexToId:s,generateExtensionId:i}=n(/*! ./tw-scratchx-utilities */"./node_modules/scratch-vm/src/extension-support/tw-scratchx-utilities.js"),c=e=>{if(""===e||" "===e||"w"===e)return{type:r.COMMAND,async:"w"===e};if("r"===e||"R"===e)return{type:r.REPORTER,async:"R"===e};if("b"===e)return{type:r.BOOLEAN,async:!1};if("h"===e)return{type:r.HAT,async:!1};throw new Error("Unknown ScratchX block type: ".concat(e))},a=(e,t)=>{const n={},r="string"==typeof(s=t)||"number"==typeof s||"boolean"==typeof s;var s;if(r&&(n.defaultValue=t),"s"===e)n.type=o.STRING,r||(n.defaultValue="");else if("n"===e)n.type=o.NUMBER,r||(n.defaultValue=0);else{if("m"!==e[0])throw new Error("Unknown ScratchX argument type: ".concat(e));{n.type=o.STRING;const t=e.split(/\.|:/)[1];n.menu=t}}return n},l=(e,t,n)=>o=>{const r=[];for(let e=0;e<t;e++)r.push(o[s(e)]);return n?new Promise(t=>{e(...r,t)}):e(...r)},u=(e,t,n)=>{const o={id:i(e),name:t.displayName||e,blocks:[],color1:"#4a4a5e",color2:"#31323f",color3:"#191a21"},r={getInfo:()=>o,_getStatus:n._getStatus};t.url&&(o.docsURI=t.url);for(const e of t.blocks){if(1===e.length){o.blocks.push("---");continue}const t=e[0],i=e[1],u=e[2],d=e.slice(3);let p="";const m=[],h=i.split(/%([\w.:]+)/g);for(let e=0;e<h.length;e++){const t=h[e];if(e%2==1){a(t);const n=Math.floor(e/2).toString(),o=d[n],r=s(n);m[r]=a(t,o),p+="[".concat(r,"]")}else p+=t}const f=c(t),g={opcode:u,blockType:f.type,text:p,arguments:m};o.blocks.push(g);const w=n[u],y=m.length;r[u]=l(w,y,f.async)}const u=t.menus;if(u){const e={};for(const t of Object.keys(u)||{}){const n={items:u[t]};e[t]=n}o.menus=e}return r},d=new Map;e.exports={register:(e,t,n)=>{const o=u(e,t,n);d.set(e,o),Scratch.extensions.register(o)},getStatus:e=>{const t=d.get(e);return t?t._getStatus():{status:0,msg:"does not exist"}},convert:u}},"./node_modules/scratch-vm/src/extension-support/tw-scratchx-utilities.js":
/*!********************************************************************************!*\
  !*** ./node_modules/scratch-vm/src/extension-support/tw-scratchx-utilities.js ***!
  \********************************************************************************/
/*! no static exports found */function(e,t){e.exports={generateExtensionId:e=>{const t=e.replace(/[^a-z0-9]/gi,"").toLowerCase();return"sbx".concat(t)},argumentIndexToId:e=>e.toString()}},"./node_modules/scratch-vm/src/util/log.js":
/*!*************************************************!*\
  !*** ./node_modules/scratch-vm/src/util/log.js ***!
  \*************************************************/
/*! no static exports found */function(e,t,n){const o=n(/*! minilog */"./node_modules/minilog/lib/web/index.js");o.enable(),e.exports=o("vm")},"./node_modules/webpack/buildin/global.js":
/*!***********************************!*\
  !*** (webpack)/buildin/global.js ***!
  \***********************************/
/*! no static exports found */function(e,t){var n;n=function(){return this}();try{n=n||new Function("return this")()}catch(e){"object"==typeof window&&(n=window)}e.exports=n}});