name: griffpatch-scratch-gui

on:
  schedule:
    - cron: '30 0 * * 3,6'
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Clone
      run: |
        git clone https://github.com/griffpatch/scratch-gui
        curl https://assets.scratch.mit.edu/internalapi/asset/b7853f557e4426412e64bb3da6531a99.svg/get/ > scratch-gui/src/lib/default-project/b7853f557e4426412e64bb3da6531a99.svg
        curl https://assets.scratch.mit.edu/internalapi/asset/e6ddc55a6ddd9cc9d84fe0b4c21e016f.svg/get/ > scratch-gui/src/lib/default-project/e6ddc55a6ddd9cc9d84fe0b4c21e016f.svg
    - name: Build
      run: |
        cd scratch-gui
        
        npm install
        npm run build
        cp LICENSE build/LICENSE
        cd ..
    - name: Upload
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: scratch-gui/build
        target_branch: griffpatch/scratch-gui
        verbose: true
        commit_message: Upload
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
